spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud
    username: cloud
    password: Qd31Ds
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    clean-disabled: true

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
